'------------------------------------------------------------------------------
' <auto-generated>
'     Este código fue generado por una herramienta.
'     Versión de runtime:4.0.30319.42000
'
'     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
'     se vuelve a generar el código.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System

Namespace My.Resources
    
    'StronglyTypedResourceBuilder generó automáticamente esta clase
    'a través de una herramienta como ResGen o Visual Studio.
    'Para agregar o quitar un miembro, edite el archivo .ResX y, a continuación, vuelva a ejecutar ResGen
    'con la opción /str o recompile su proyecto de VS.
    '''<summary>
    '''  Clase de recurso fuertemente tipado, para buscar cadenas traducidas, etc.
    '''</summary>
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0"),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute(),  _
     Global.Microsoft.VisualBasic.HideModuleNameAttribute()>  _
    Friend Module Resources
        
        Private resourceMan As Global.System.Resources.ResourceManager
        
        Private resourceCulture As Global.System.Globalization.CultureInfo
        
        '''<summary>
        '''  Devuelve la instancia de ResourceManager almacenada en caché utilizada por esta clase.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend ReadOnly Property ResourceManager() As Global.System.Resources.ResourceManager
            Get
                If Object.ReferenceEquals(resourceMan, Nothing) Then
                    Dim temp As Global.System.Resources.ResourceManager = New Global.System.Resources.ResourceManager("BETTATECH.Resources", GetType(Resources).Assembly)
                    resourceMan = temp
                End If
                Return resourceMan
            End Get
        End Property
        
        '''<summary>
        '''  Reemplaza la propiedad CurrentUICulture del subproceso actual para todas las
        '''  búsquedas de recursos mediante esta clase de recurso fuertemente tipado.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Property Culture() As Global.System.Globalization.CultureInfo
            Get
                Return resourceCulture
            End Get
            Set
                resourceCulture = value
            End Set
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a a
        '''a`baco
        '''a`brego
        '''a`brigo
        '''a`bsida
        '''a`bside
        '''a`bsit
        '''a`cana
        '''a`caro
        '''a`cates
        '''a`cere
        '''a`cida
        '''a`cido
        '''a`cigos
        '''a`cimo
        '''a`coro
        '''a`crata
        '''a`cuea
        '''a`cueo
        '''a`cula
        '''a`faca
        '''a`fila
        '''a`filo
        '''a`fona
        '''a`fono
        '''a`frica
        '''a`frico
        '''a`gape
        '''a`gata
        '''a`gil
        '''a`gilmente
        '''a`gora
        '''a`guila
        '''a`l
        '''a`labe
        '''a`laga
        '''a`lamo
        '''a`lbum
        '''a`lcali
        '''a`lgebra
        '''a`lgica
        '''a`lgido
        '''a`lica
        '''a`liger
        '''a`limo
        '''a`loe
        '''a`lsine
        '''a`lveo
        '''a`mago
        '''a`mala
        '''a`malo
        '''a`mbar
        '''a`mbito
        '''a`mel
        '''a`nade
        '''a`ncora
        '''a`ndito
        '''a`nfora
        '''a`ngaro
        '''a`ngel
        '''a`ngela
        '''a`ngelus [resto de la cadena truncado]&quot;;.
        '''</summary>
        Friend ReadOnly Property palabras() As String
            Get
                Return ResourceManager.GetString("palabras", resourceCulture)
            End Get
        End Property
    End Module
End Namespace
